const works = [
  {
    title: "You Are Speed",
    description: "A solo-made speedrunning game I built to celebrate my 25th birthday, featuring handcrafted levels, an advanced movement system, and personal storytelling narrated by me across each stage. A personal project to test my level design and narrative design capabilities.",
    tag: "Steam",
    link: "https://store.steampowered.com/app/2330060/You_Are_Speed/",
    image: "images/PhotoshopImages/TemplateCapsules-PageBackground.png",
  },
  {
    title: "Programmer At Capricia Productions",
    description: "A game studio I joined as a Programmer and Product Contributor, coordinating between art, design, and engineering teams. Prototyped features, standardized technical documentation, and provided cross-team implementation support.",
    tag: "Studio",
    link: "https://www.capriciaproductions.com/",
    image: "images/Capricia2Wide.png",
  },
  {
    title: "Director At Fuel Ink",
    description: "A 15-person studio where I served as Product Manager and Director, delivering a playable demo in four months. Built Agile workflows, recruited the team, and aligned stakeholder expectations with realistic goals.",
    tag: "Studio",
    link: "#",
    image: "images/FuelInkPrev.png",
  },
  {
    title: "Red Scarf Platformer",
    description: "An indie platformer I founded and shipped solo, reaching 30,000+ players. Built the full experience in Godot from scratch and negotiated a post-release selling contract.",
    tag: "Armor Games",
    link: "https://armorgames.com/red-scarf-platformer-game/19300",
    image: "images/RedScarfPreview.png",
  },
  {
    title: "Idiotic The Game",
    description: "An indie game I independently designed, programmed, and marketed over two years to a Steam release, accumulating over 4 million trailer views. Managed QA, iterated on user feedback, and owned the full product lifecycle.",
    tag: "Steam",
    link: "https://store.steampowered.com/app/1746520/IDIOTIC_The_Game/",
    image: "images/IdioticHeader.jpg",
  },
  {
    title: "Jeinfeld",
    description: "My first Game Jam at Global Game Jam — 48 hours at IAC with a team of 11 developers using Unity and Blender.",
    tag: "Game Jam",
    link: "https://globalgamejam.org/games/2024/jeinfeld-7",
    image: "images/JeinFeld.png",
  },
  {
    title: "Unreal Engine Sequencer Works",
    description: "A YouTube playlist of cinematic sequences made using Unreal Engine Sequencer and Premiere.",
    tag: "YouTube",
    link: "https://www.youtube.com/playlist?list=PLeyBti4kPK4_LA9QdQy52xl3piuqxisWM",
    image: "images/UnrealSequencer.png",
  },
  {
    title: "Unreal Engine YouTube Tutorials",
    description: "A YouTube playlist of tutorials focused on Unreal Engine blueprints.",
    tag: "YouTube",
    link: "https://www.youtube.com/playlist?list=PLeyBti4kPK4-inWoUPMFt2I69SmMbHCI2",
    image: "images/GeoCacheTutThumbnail.png",
  },
  {
    title: "C++ Time API in Unreal Engine",
    description: "A personal project practicing HTTP calls and using an external API inside Unreal Engine.",
    tag: "GitHub",
    link: "https://github.com/Ayen11/Time-API",
    image: "images/CPPAPITime.png",
  },
  {
    title: "Other Projects",
    description: "Photoshop and Blender work — posters, 3D architectural previews, fan art, and creative personal projects.",
    tag: "Gallery",
    link: "gallery.html",
    image: "images/ArtPreview.png",
    extraClass: "card--gallery",
    dividerBefore: true,
  },
];
